WeakMap and WeakSet
javascript-tutorial/de.javascript.info pull request #196
Opened 2023-12-15 16:45 UTC by behrends

2023-12-16 14:53 UTC, J-Cake requested changes
+1

2023-12-16 14:53 UTC, J-Cake commented on 1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
> +Es bereinigt sich automatisch. Der Kompromiss ist, dass wir nicht darüber iterieren können, wir können "alle gelesenen Nachrichten" daraus nicht direkt erhalten. Aber wir können dies erreichen, indem
Die Übersetzung passt zum Kontext nicht. Hier ist warscheinlich maschinell übersetzt worden?

> *... indem wir über alle Nachrichten iterieren und diejenigen aussortieren, die nicht im Set sind.

2023-12-16 14:53 UTC, J-Cake commented on 1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/solution.md
[Variabeln sollten möglichst ungeändert bleiben](https://github.com/javascript-tutorial/de.javascript.info/tree/master#text-in-code-blocks)

2023-12-16 14:53 UTC, J-Cake commented on 1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
> +Die Frage lautet nun: Welche Datenstruktur würdest Du vorschlagen, um die Information zu speichern: „Wann wurde die Nachricht gelesen?“.
Die besonderen Anführungszeichten gefallen mir, aber ist nicht konsistent mit der bisherigen Übersetzungsleistung... Müsste leider auch geändert werden :(

2023-12-17 12:12 UTC, behrends commented
Done

2023-12-17 14:41 UTC, merged